### ISSUE TITLE
Pioneer-3DX Gazebo Support

### ISSUE THREAD

**Issue by allenh1** [allenh1/p2os#37]
There is a model, but no motion. I will be working on this for the next release.

**Comment by dmiklic** [comment]
I am currenly getting a crash with on Ubuntu 16.04 with ROS Kinetic, Gazebo 7 and `pioneer3dx.gazebo.launch`:

```
Error [Param.cc:451] Unable to set value [-nan -nan -nan] for key[size]
gzclient: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:630: virtual void Ogre::Node::setScale(const Ogre::Vector3&): Assertion `!inScale.isNaN() && "Invalid vector supplied as parameter"' failed.
Aborted (core dumped)
```

Can anyone confirm this behavior?

**Comment by allenh1** [comment]
Hm... I will try this later. I have not done much with this... I will assume some protocol has since changed and completely broke the Gazebo support here.

As I am not very knowledgeable about Gazebo, I'm probably not the best person to look into this.

**Comment by dmiklic** [comment]
I can look into it, as I need this functionality. As I'm also new to Gazebo, it might take a while to get things right. For now, I have [asked for help](http://answers.gazebosim.org/question/15816/gazebo-crashes-when-spawning-robot-from-urdf/) at Gazebo answers.

**Comment by allenh1** [comment]
Sounds good. Thank you very much!

By the way, there is a repo that holds a working copy of p2os gazebo, though I do not remember the name of it (as I frequently just use stage).

On Apr 11, 2017 6:04 AM, Damjan Miklic <notifications@github.com> wrote:

I can look into it, as I need this functionality. As I'm also new to Gazebo, it might take a while to get things right. For now, I have asked for help<http://answers.gazebosim.org/question/15816/gazebo-crashes-when-spawning-robot-from-urdf/> at Gazebo answers.

**Comment by dmiklic** [comment]
I have fixed the bug that was causing the crash, so now I can see and control the robot in Gazebo. There was also an issue with the `<visual>` tags due to [this SDF bug](https://bitbucket.org/osrf/sdformat/issues/132/parser-does-not-handle-urdf-material) that prevented material rendering in Gazebo, which has been fixed. 

Before making a pull request I'd like to clean up the model some more and do some tests to make sure it behaves reasonably. You can follow the progress here:

https://github.com/larics/p2os/tree/bugfix-urdf-p3dx/p2os_urdf

**Comment by allenh1** [comment]
Nice work! Thanks! I look forward to your PR.
